[[dependency]]
name = "nvrhi"
rel_path = "nvrhi"
libs = ["nvrhi_vk", "rtxmu", "nvrhi"]
cmake_options = [
    "-DNVRHI_INSTALL=OFF",
    "-DNVRHI_WITH_RTXMU=ON",
    "-DNVRHI_WITH_VALIDATION=ON",
    "-DNVRHI_WITH_VULKAN=ON",
    "-DNVRHI_WITH_DX11=OFF",
    "-DNVRHI_WITH_DX12=OFF",
    "-DNVRHI_WITH_NVAPI=OFF",
    "-DNVRHI_BUILD_SHARED=OFF",
    "-DRTXMU_WITH_D3D12=OFF",
    "-DRTXMU_WITH_VULKAN=ON",
    "-DVULKAN_HEADERS_ENABLE_INSTALL=OFF",
]

[[dependency]]
name = "vk-bootstrap"
rel_path = "vk-bootstrap"
libs = ["vk-bootstrap"]
cmake_options = [
    "-DBUILD_SHARED_LIBS=OFF",
    "-DGLFW_BUILD_TESTS=OFF",
    "-DVK_BOOTSTRAP_TEST=OFF",
    "-DVK_BOOTSTRAP_DISABLE_WARNINGS=ON",
    "-DVK_BOOTSTRAP_INSTALL=OFF",
    "-DUSE_MSVC_RUNTIME_LIBRARY_DLL=OFF"
]

[[dependency]]
name = "SPIRV-Tools"
rel_path = "spirv-tools-shim"
libs = ["SPIRV-Tools-opt", "SPIRV-Tools"]
cmake_options = [
    "-DBUILD_SHARED_LIBS=OFF",
]
