// Generated by Vidl - DO NOT MODIFY : see vidl.py
#include <cstdint>



struct VIDLHandler
{

    virtual void HandleCmd( void* cmd )
    {
        uint64_t magic = *(uint64_t*)cmd;
        switch ( magic )
        {
        }
    }
};
