// Generated by Vidl - DO NOT MODIFY : see vidl.py
#include <cstdint>

struct VIDL_vhDestroyTexture
{
    static constexpr uint64_t kMagic = 0xC090699A;
    uint64_t MAGIC = kMagic;
    vhTexture texture;

    VIDL_vhDestroyTexture() = default;

    VIDL_vhDestroyTexture(vhTexture _texture)
        : texture(_texture) {}
};

struct VIDL_vhCreateTexture
{
    static constexpr uint64_t kMagic = 0xB40533D3;
    uint64_t MAGIC = kMagic;
    vhTexture texture;
    nvrhi::TextureDimension target;
    glm::ivec3 dimensions;
    int numMips;
    int numLayers;
    nvrhi::Format format;
    uint64_t flag = VRHI_TEXTURE_NONE | VRHI_SAMPLER_NONE;
    const std::vector<uint8_t>* data = nullptr;

    VIDL_vhCreateTexture() = default;

    VIDL_vhCreateTexture(vhTexture _texture, nvrhi::TextureDimension _target, glm::ivec3 _dimensions, int _numMips, int _numLayers, nvrhi::Format _format, uint64_t _flag, const std::vector<uint8_t>* _data)
        : texture(_texture), target(_target), dimensions(_dimensions), numMips(_numMips), numLayers(_numLayers), format(_format), flag(_flag), data(_data) {}
};

struct VIDL_vhFlushInternal
{
    static constexpr uint64_t kMagic = 0x83140D26;
    uint64_t MAGIC = kMagic;
    std::atomic<bool>* fence;

    VIDL_vhFlushInternal() = default;

    VIDL_vhFlushInternal(std::atomic<bool>* _fence)
        : fence(_fence) {}
};

struct VIDLHandler
{
    virtual void Handle_vhDestroyTexture( VIDL_vhDestroyTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateTexture( VIDL_vhCreateTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhFlushInternal( VIDL_vhFlushInternal* cmd ) { (void) cmd; };

    virtual void HandleCmd( void* cmd )
    {
        uint64_t magic = *(uint64_t*)cmd;
        switch ( magic )
        {
        case 0xC090699A:
            Handle_vhDestroyTexture( (VIDL_vhDestroyTexture*) cmd );
            break;
        case 0xB40533D3:
            Handle_vhCreateTexture( (VIDL_vhCreateTexture*) cmd );
            break;
        case 0x83140D26:
            Handle_vhFlushInternal( (VIDL_vhFlushInternal*) cmd );
            break;
        }
    }
};