// Generated by Vidl - DO NOT MODIFY : see vidl.py
#include <cstdint>

struct VIDL_vhResetTexture
{
    static constexpr uint64_t kMagic = 0xE74D1798;
    uint64_t MAGIC = kMagic;
    vhTexture texture;

    VIDL_vhResetTexture() = default;

    VIDL_vhResetTexture(vhTexture _texture)
        : texture(_texture) {}
};

struct VIDL_vhResetBuffer
{
    static constexpr uint64_t kMagic = 0x19331E16;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;

    VIDL_vhResetBuffer() = default;

    VIDL_vhResetBuffer(vhBuffer _buffer)
        : buffer(_buffer) {}
};

struct VIDL_vhDestroyTexture
{
    static constexpr uint64_t kMagic = 0xC090699A;
    uint64_t MAGIC = kMagic;
    vhTexture texture;

    VIDL_vhDestroyTexture() = default;

    VIDL_vhDestroyTexture(vhTexture _texture)
        : texture(_texture) {}
};

struct VIDL_vhCreateTexture
{
    static constexpr uint64_t kMagic = 0xB40533D3;
    uint64_t MAGIC = kMagic;
    vhTexture texture;
    nvrhi::TextureDimension target;
    glm::ivec3 dimensions;
    int numMips;
    int numLayers;
    nvrhi::Format format;
    uint64_t flag = VRHI_TEXTURE_NONE | VRHI_SAMPLER_NONE;
    const vhMem* data = nullptr;

    VIDL_vhCreateTexture() = default;

    VIDL_vhCreateTexture(vhTexture _texture, nvrhi::TextureDimension _target, glm::ivec3 _dimensions, int _numMips, int _numLayers, nvrhi::Format _format, uint64_t _flag, const vhMem* _data)
        : texture(_texture), target(_target), dimensions(_dimensions), numMips(_numMips), numLayers(_numLayers), format(_format), flag(_flag), data(_data) {}
};

struct VIDL_vhUpdateTexture
{
    static constexpr uint64_t kMagic = 0x79B006BB;
    uint64_t MAGIC = kMagic;
    vhTexture texture;
    int startMips = 0;
    int startLayers = 0;
    int numMips = 1;
    int numLayers = 1;
    const vhMem* data = nullptr;

    VIDL_vhUpdateTexture() = default;

    VIDL_vhUpdateTexture(vhTexture _texture, int _startMips, int _startLayers, int _numMips, int _numLayers, const vhMem* _data)
        : texture(_texture), startMips(_startMips), startLayers(_startLayers), numMips(_numMips), numLayers(_numLayers), data(_data) {}
};

struct VIDL_vhReadTextureSlow
{
    static constexpr uint64_t kMagic = 0x3BDDAB67;
    uint64_t MAGIC = kMagic;
    vhTexture texture;
    int mip = 0;
    int layer = 0;
    vhMem* outData = nullptr;

    VIDL_vhReadTextureSlow() = default;

    VIDL_vhReadTextureSlow(vhTexture _texture, int _mip, int _layer, vhMem* _outData)
        : texture(_texture), mip(_mip), layer(_layer), outData(_outData) {}
};

struct VIDL_vhBlitTexture
{
    static constexpr uint64_t kMagic = 0xD7782E0F;
    uint64_t MAGIC = kMagic;
    vhTexture dst;
    vhTexture src;
    int dstMip = 0;
    int srcMip = 0;
    int dstLayer = 0;
    int srcLayer = 0;
    glm::ivec3 dstOffset = glm::ivec3( 0 );
    glm::ivec3 srcOffset = glm::ivec3( 0 );
    glm::ivec3 extent = glm::ivec3( 0 );

    VIDL_vhBlitTexture() = default;

    VIDL_vhBlitTexture(vhTexture _dst, vhTexture _src, int _dstMip, int _srcMip, int _dstLayer, int _srcLayer, glm::ivec3 _dstOffset, glm::ivec3 _srcOffset, glm::ivec3 _extent)
        : dst(_dst), src(_src), dstMip(_dstMip), srcMip(_srcMip), dstLayer(_dstLayer), srcLayer(_srcLayer), dstOffset(_dstOffset), srcOffset(_srcOffset), extent(_extent) {}
};

struct VIDL_vhCreateVertexBuffer
{
    static constexpr uint64_t kMagic = 0xBBF8D184;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const char* name;
    const vhMem* data;
    const vhVertexLayout layout;
    uint64_t numVerts = 0;
    uint16_t flags = VRHI_BUFFER_NONE;

    VIDL_vhCreateVertexBuffer() = default;

    VIDL_vhCreateVertexBuffer(vhBuffer _buffer, const char* _name, const vhMem* _data, const vhVertexLayout _layout, uint64_t _numVerts, uint16_t _flags)
        : buffer(_buffer), name(_name), data(_data), layout(_layout), numVerts(_numVerts), flags(_flags) {}
};

struct VIDL_vhUpdateVertexBuffer
{
    static constexpr uint64_t kMagic = 0x57AF47B4;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const vhMem* data;
    uint64_t offset = 0;
    uint64_t numVerts = 0;

    VIDL_vhUpdateVertexBuffer() = default;

    VIDL_vhUpdateVertexBuffer(vhBuffer _buffer, const vhMem* _data, uint64_t _offset, uint64_t _numVerts)
        : buffer(_buffer), data(_data), offset(_offset), numVerts(_numVerts) {}
};

struct VIDL_vhCreateIndexBuffer
{
    static constexpr uint64_t kMagic = 0x22AE59E6;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const char* name;
    const vhMem* data;
    uint64_t numIndices = 0;
    uint16_t flags = VRHI_BUFFER_NONE;

    VIDL_vhCreateIndexBuffer() = default;

    VIDL_vhCreateIndexBuffer(vhBuffer _buffer, const char* _name, const vhMem* _data, uint64_t _numIndices, uint16_t _flags)
        : buffer(_buffer), name(_name), data(_data), numIndices(_numIndices), flags(_flags) {}
};

struct VIDL_vhUpdateIndexBuffer
{
    static constexpr uint64_t kMagic = 0x6B219F18;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const vhMem* data;
    uint64_t offset = 0;
    uint64_t numIndices = 0;

    VIDL_vhUpdateIndexBuffer() = default;

    VIDL_vhUpdateIndexBuffer(vhBuffer _buffer, const vhMem* _data, uint64_t _offset, uint64_t _numIndices)
        : buffer(_buffer), data(_data), offset(_offset), numIndices(_numIndices) {}
};

struct VIDL_vhDestroyBuffer
{
    static constexpr uint64_t kMagic = 0x3A87A73E;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;

    VIDL_vhDestroyBuffer() = default;

    VIDL_vhDestroyBuffer(vhBuffer _buffer)
        : buffer(_buffer) {}
};

struct VIDL_vhFlushInternal
{
    static constexpr uint64_t kMagic = 0x83140D26;
    uint64_t MAGIC = kMagic;
    std::atomic<bool>* fence;
    bool waitForGPU = false;

    VIDL_vhFlushInternal() = default;

    VIDL_vhFlushInternal(std::atomic<bool>* _fence, bool _waitForGPU)
        : fence(_fence), waitForGPU(_waitForGPU) {}
};

struct VIDLHandler
{
    virtual void Handle_vhResetTexture( VIDL_vhResetTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhResetBuffer( VIDL_vhResetBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhDestroyTexture( VIDL_vhDestroyTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateTexture( VIDL_vhCreateTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhUpdateTexture( VIDL_vhUpdateTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhReadTextureSlow( VIDL_vhReadTextureSlow* cmd ) { (void) cmd; };
    virtual void Handle_vhBlitTexture( VIDL_vhBlitTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateVertexBuffer( VIDL_vhCreateVertexBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhUpdateVertexBuffer( VIDL_vhUpdateVertexBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateIndexBuffer( VIDL_vhCreateIndexBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhUpdateIndexBuffer( VIDL_vhUpdateIndexBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhDestroyBuffer( VIDL_vhDestroyBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhFlushInternal( VIDL_vhFlushInternal* cmd ) { (void) cmd; };

    virtual void HandleCmd( void* cmd )
    {
        uint64_t magic = *(uint64_t*)cmd;
        switch ( magic )
        {
        case 0xE74D1798:
            Handle_vhResetTexture( (VIDL_vhResetTexture*) cmd );
            break;
        case 0x19331E16:
            Handle_vhResetBuffer( (VIDL_vhResetBuffer*) cmd );
            break;
        case 0xC090699A:
            Handle_vhDestroyTexture( (VIDL_vhDestroyTexture*) cmd );
            break;
        case 0xB40533D3:
            Handle_vhCreateTexture( (VIDL_vhCreateTexture*) cmd );
            break;
        case 0x79B006BB:
            Handle_vhUpdateTexture( (VIDL_vhUpdateTexture*) cmd );
            break;
        case 0x3BDDAB67:
            Handle_vhReadTextureSlow( (VIDL_vhReadTextureSlow*) cmd );
            break;
        case 0xD7782E0F:
            Handle_vhBlitTexture( (VIDL_vhBlitTexture*) cmd );
            break;
        case 0xBBF8D184:
            Handle_vhCreateVertexBuffer( (VIDL_vhCreateVertexBuffer*) cmd );
            break;
        case 0x57AF47B4:
            Handle_vhUpdateVertexBuffer( (VIDL_vhUpdateVertexBuffer*) cmd );
            break;
        case 0x22AE59E6:
            Handle_vhCreateIndexBuffer( (VIDL_vhCreateIndexBuffer*) cmd );
            break;
        case 0x6B219F18:
            Handle_vhUpdateIndexBuffer( (VIDL_vhUpdateIndexBuffer*) cmd );
            break;
        case 0x3A87A73E:
            Handle_vhDestroyBuffer( (VIDL_vhDestroyBuffer*) cmd );
            break;
        case 0x83140D26:
            Handle_vhFlushInternal( (VIDL_vhFlushInternal*) cmd );
            break;
        }
    }
};