// Generated by Vidl - DO NOT MODIFY : see vidl.py
#include <cstdint>

struct VIDL_vhResizeCleanup
{
    static constexpr uint64_t kMagic = 0xF3F4A7CF;
    uint64_t MAGIC = kMagic;

    VIDL_vhResizeCleanup() = default;
};

struct VIDL_vhBeginTimerQuery
{
    static constexpr uint64_t kMagic = 0x178A2421;
    uint64_t MAGIC = kMagic;
    vhTimerID timerID;

    VIDL_vhBeginTimerQuery() = default;

    VIDL_vhBeginTimerQuery(vhTimerID _timerID)
        : timerID(_timerID) {}
};

struct VIDL_vhEndTimerQuery
{
    static constexpr uint64_t kMagic = 0x130A84AE;
    uint64_t MAGIC = kMagic;
    vhTimerID timerID;

    VIDL_vhEndTimerQuery() = default;

    VIDL_vhEndTimerQuery(vhTimerID _timerID)
        : timerID(_timerID) {}
};

struct VIDL_vhBeginMarker
{
    static constexpr uint64_t kMagic = 0x2631B4CA;
    uint64_t MAGIC = kMagic;
    const std::string name;

    VIDL_vhBeginMarker() = default;

    VIDL_vhBeginMarker(const std::string& _name)
        : name(_name) {}
};

struct VIDL_vhEndMarker
{
    static constexpr uint64_t kMagic = 0xFA453E7B;
    uint64_t MAGIC = kMagic;

    VIDL_vhEndMarker() = default;
};

struct VIDL_vhCaptureStart
{
    static constexpr uint64_t kMagic = 0x45A5468F;
    uint64_t MAGIC = kMagic;

    VIDL_vhCaptureStart() = default;
};

struct VIDL_vhCaptureEnd
{
    static constexpr uint64_t kMagic = 0x165DAA75;
    uint64_t MAGIC = kMagic;

    VIDL_vhCaptureEnd() = default;
};

struct VIDL_vhResetTexture
{
    static constexpr uint64_t kMagic = 0xE74D1798;
    uint64_t MAGIC = kMagic;
    vhTexture texture;

    VIDL_vhResetTexture() = default;

    VIDL_vhResetTexture(vhTexture _texture)
        : texture(_texture) {}
};

struct VIDL_vhResetBuffer
{
    static constexpr uint64_t kMagic = 0x19331E16;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;

    VIDL_vhResetBuffer() = default;

    VIDL_vhResetBuffer(vhBuffer _buffer)
        : buffer(_buffer) {}
};

struct VIDL_vhDestroyTexture
{
    static constexpr uint64_t kMagic = 0xC090699A;
    uint64_t MAGIC = kMagic;
    vhTexture texture;

    VIDL_vhDestroyTexture() = default;

    VIDL_vhDestroyTexture(vhTexture _texture)
        : texture(_texture) {}
};

struct VIDL_vhCreateTexture
{
    static constexpr uint64_t kMagic = 0xB40533D3;
    uint64_t MAGIC = kMagic;
    vhTexture texture;
    const char* name;
    nvrhi::TextureDimension target;
    glm::ivec3 dimensions;
    int numMips;
    int numLayers;
    nvrhi::Format format;
    uint64_t flag = VRHI_TEXTURE_NONE | VRHI_SAMPLER_NONE;
    const vhMem* data = nullptr;

    VIDL_vhCreateTexture() = default;

    VIDL_vhCreateTexture(vhTexture _texture, const char* _name, nvrhi::TextureDimension _target, glm::ivec3 _dimensions, int _numMips, int _numLayers, nvrhi::Format _format, uint64_t _flag, const vhMem* _data)
        : texture(_texture), name(_name), target(_target), dimensions(_dimensions), numMips(_numMips), numLayers(_numLayers), format(_format), flag(_flag), data(_data) {}
};

struct VIDL_vhUpdateTexture
{
    static constexpr uint64_t kMagic = 0x79B006BB;
    uint64_t MAGIC = kMagic;
    vhTexture texture;
    int startMips = 0;
    int startLayers = 0;
    int numMips = 1;
    int numLayers = 1;
    const vhMem* data = nullptr;

    VIDL_vhUpdateTexture() = default;

    VIDL_vhUpdateTexture(vhTexture _texture, int _startMips, int _startLayers, int _numMips, int _numLayers, const vhMem* _data)
        : texture(_texture), startMips(_startMips), startLayers(_startLayers), numMips(_numMips), numLayers(_numLayers), data(_data) {}
};

struct VIDL_vhReadTextureSlow
{
    static constexpr uint64_t kMagic = 0x3BDDAB67;
    uint64_t MAGIC = kMagic;
    vhTexture texture;
    int mip = 0;
    int layer = 0;
    vhMem* outData = nullptr;

    VIDL_vhReadTextureSlow() = default;

    VIDL_vhReadTextureSlow(vhTexture _texture, int _mip, int _layer, vhMem* _outData)
        : texture(_texture), mip(_mip), layer(_layer), outData(_outData) {}
};

struct VIDL_vhBlitTexture
{
    static constexpr uint64_t kMagic = 0xD7782E0F;
    uint64_t MAGIC = kMagic;
    vhTexture dst;
    vhTexture src;
    int dstMip = 0;
    int srcMip = 0;
    int dstLayer = 0;
    int srcLayer = 0;
    glm::ivec3 dstOffset = glm::ivec3( 0 );
    glm::ivec3 srcOffset = glm::ivec3( 0 );
    glm::ivec3 extent = glm::ivec3( 0 );

    VIDL_vhBlitTexture() = default;

    VIDL_vhBlitTexture(vhTexture _dst, vhTexture _src, int _dstMip, int _srcMip, int _dstLayer, int _srcLayer, glm::ivec3 _dstOffset, glm::ivec3 _srcOffset, glm::ivec3 _extent)
        : dst(_dst), src(_src), dstMip(_dstMip), srcMip(_srcMip), dstLayer(_dstLayer), srcLayer(_srcLayer), dstOffset(_dstOffset), srcOffset(_srcOffset), extent(_extent) {}
};

struct VIDL_vhCreateVertexBuffer
{
    static constexpr uint64_t kMagic = 0xBBF8D184;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const char* name;
    const vhMem* data;
    const vhVertexLayout layout;
    uint64_t numVerts = 0;
    uint16_t flags = VRHI_BUFFER_NONE;

    VIDL_vhCreateVertexBuffer() = default;

    VIDL_vhCreateVertexBuffer(vhBuffer _buffer, const char* _name, const vhMem* _data, const vhVertexLayout _layout, uint64_t _numVerts, uint16_t _flags)
        : buffer(_buffer), name(_name), data(_data), layout(_layout), numVerts(_numVerts), flags(_flags) {}
};

struct VIDL_vhUpdateVertexBuffer
{
    static constexpr uint64_t kMagic = 0x57AF47B4;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const vhMem* data;
    uint64_t offsetVerts = 0;
    uint64_t numVerts = 0;

    VIDL_vhUpdateVertexBuffer() = default;

    VIDL_vhUpdateVertexBuffer(vhBuffer _buffer, const vhMem* _data, uint64_t _offsetVerts, uint64_t _numVerts)
        : buffer(_buffer), data(_data), offsetVerts(_offsetVerts), numVerts(_numVerts) {}
};

struct VIDL_vhCreateIndexBuffer
{
    static constexpr uint64_t kMagic = 0x22AE59E6;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const char* name;
    const vhMem* data;
    uint64_t numIndices = 0;
    uint16_t flags = VRHI_BUFFER_NONE;

    VIDL_vhCreateIndexBuffer() = default;

    VIDL_vhCreateIndexBuffer(vhBuffer _buffer, const char* _name, const vhMem* _data, uint64_t _numIndices, uint16_t _flags)
        : buffer(_buffer), name(_name), data(_data), numIndices(_numIndices), flags(_flags) {}
};

struct VIDL_vhUpdateIndexBuffer
{
    static constexpr uint64_t kMagic = 0x6B219F18;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const vhMem* data;
    uint64_t offsetIndices = 0;
    uint64_t numIndices = 0;

    VIDL_vhUpdateIndexBuffer() = default;

    VIDL_vhUpdateIndexBuffer(vhBuffer _buffer, const vhMem* _data, uint64_t _offsetIndices, uint64_t _numIndices)
        : buffer(_buffer), data(_data), offsetIndices(_offsetIndices), numIndices(_numIndices) {}
};

struct VIDL_vhCreateUniformBuffer
{
    static constexpr uint64_t kMagic = 0x2EFADC4C;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const char* name;
    const vhMem* data;
    uint64_t size = 0;
    uint16_t flags = VRHI_BUFFER_NONE;

    VIDL_vhCreateUniformBuffer() = default;

    VIDL_vhCreateUniformBuffer(vhBuffer _buffer, const char* _name, const vhMem* _data, uint64_t _size, uint16_t _flags)
        : buffer(_buffer), name(_name), data(_data), size(_size), flags(_flags) {}
};

struct VIDL_vhUpdateUniformBuffer
{
    static constexpr uint64_t kMagic = 0xD6050AA7;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const vhMem* data;
    uint64_t offset = 0;
    uint64_t size = 0;

    VIDL_vhUpdateUniformBuffer() = default;

    VIDL_vhUpdateUniformBuffer(vhBuffer _buffer, const vhMem* _data, uint64_t _offset, uint64_t _size)
        : buffer(_buffer), data(_data), offset(_offset), size(_size) {}
};

struct VIDL_vhCreateStorageBuffer
{
    static constexpr uint64_t kMagic = 0x797A3950;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const char* name;
    const vhMem* data;
    uint64_t size = 0;
    uint16_t flags = VRHI_BUFFER_COMPUTE_READ_WRITE;
    uint32_t stride = 0;
    nvrhi::Format format = nvrhi::Format::UNKNOWN;

    VIDL_vhCreateStorageBuffer() = default;

    VIDL_vhCreateStorageBuffer(vhBuffer _buffer, const char* _name, const vhMem* _data, uint64_t _size, uint16_t _flags, uint32_t _stride, nvrhi::Format _format)
        : buffer(_buffer), name(_name), data(_data), size(_size), flags(_flags), stride(_stride), format(_format) {}
};

struct VIDL_vhUpdateStorageBuffer
{
    static constexpr uint64_t kMagic = 0x6153A4D9;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;
    const vhMem* data;
    uint64_t offset = 0;
    uint64_t size = 0;

    VIDL_vhUpdateStorageBuffer() = default;

    VIDL_vhUpdateStorageBuffer(vhBuffer _buffer, const vhMem* _data, uint64_t _offset, uint64_t _size)
        : buffer(_buffer), data(_data), offset(_offset), size(_size) {}
};

struct VIDL_vhBlitBuffer
{
    static constexpr uint64_t kMagic = 0x15BFFC71;
    uint64_t MAGIC = kMagic;
    vhBuffer dst;
    vhBuffer src;
    uint64_t dstOffset = 0;
    uint64_t srcOffset = 0;
    uint64_t size = 0;

    VIDL_vhBlitBuffer() = default;

    VIDL_vhBlitBuffer(vhBuffer _dst, vhBuffer _src, uint64_t _dstOffset, uint64_t _srcOffset, uint64_t _size)
        : dst(_dst), src(_src), dstOffset(_dstOffset), srcOffset(_srcOffset), size(_size) {}
};

struct VIDL_vhDestroyBuffer
{
    static constexpr uint64_t kMagic = 0x3A87A73E;
    uint64_t MAGIC = kMagic;
    vhBuffer buffer;

    VIDL_vhDestroyBuffer() = default;

    VIDL_vhDestroyBuffer(vhBuffer _buffer)
        : buffer(_buffer) {}
};

struct VIDL_vhCreateAS
{
    static constexpr uint64_t kMagic = 0xB7F81FE0;
    uint64_t MAGIC = kMagic;
    vhAccelStruct as;
    const nvrhi::rt::AccelStructDesc desc;

    VIDL_vhCreateAS() = default;

    VIDL_vhCreateAS(vhAccelStruct _as, const nvrhi::rt::AccelStructDesc& _desc)
        : as(_as), desc(_desc) {}
};

struct VIDL_vhDestroyAS
{
    static constexpr uint64_t kMagic = 0xC034F291;
    uint64_t MAGIC = kMagic;
    vhAccelStruct as;

    VIDL_vhDestroyAS() = default;

    VIDL_vhDestroyAS(vhAccelStruct _as)
        : as(_as) {}
};

struct VIDL_vhBuildBLAS
{
    static constexpr uint64_t kMagic = 0xDBB4E9AB;
    uint64_t MAGIC = kMagic;
    vhAccelStruct blas;
    std::vector< nvrhi::rt::GeometryDesc > geometries;

    VIDL_vhBuildBLAS() = default;

    VIDL_vhBuildBLAS(vhAccelStruct _blas, std::vector< nvrhi::rt::GeometryDesc > _geometries)
        : blas(_blas), geometries(_geometries) {}
};

struct VIDL_vhBuildTLAS
{
    static constexpr uint64_t kMagic = 0xBAF93377;
    uint64_t MAGIC = kMagic;
    vhAccelStruct tlas;
    std::vector< nvrhi::rt::InstanceDesc > instances;

    VIDL_vhBuildTLAS() = default;

    VIDL_vhBuildTLAS(vhAccelStruct _tlas, std::vector< nvrhi::rt::InstanceDesc > _instances)
        : tlas(_tlas), instances(_instances) {}
};

struct VIDL_vhCreateRTPipeline
{
    static constexpr uint64_t kMagic = 0xF080D7EA;
    uint64_t MAGIC = kMagic;
    vhRTPipeline pipeline;
    const nvrhi::rt::PipelineDesc desc;

    VIDL_vhCreateRTPipeline() = default;

    VIDL_vhCreateRTPipeline(vhRTPipeline _pipeline, const nvrhi::rt::PipelineDesc& _desc)
        : pipeline(_pipeline), desc(_desc) {}
};

struct VIDL_vhDestroyRTPipeline
{
    static constexpr uint64_t kMagic = 0x5AA337AF;
    uint64_t MAGIC = kMagic;
    vhRTPipeline pipeline;

    VIDL_vhDestroyRTPipeline() = default;

    VIDL_vhDestroyRTPipeline(vhRTPipeline _pipeline)
        : pipeline(_pipeline) {}
};

struct VIDL_vhCreateShaderTable
{
    static constexpr uint64_t kMagic = 0x9DDDDA05;
    uint64_t MAGIC = kMagic;
    vhShaderTable table;
    vhRTPipeline pipeline;

    VIDL_vhCreateShaderTable() = default;

    VIDL_vhCreateShaderTable(vhShaderTable _table, vhRTPipeline _pipeline)
        : table(_table), pipeline(_pipeline) {}
};

struct VIDL_vhDestroyShaderTable
{
    static constexpr uint64_t kMagic = 0x6950CD93;
    uint64_t MAGIC = kMagic;
    vhShaderTable table;

    VIDL_vhDestroyShaderTable() = default;

    VIDL_vhDestroyShaderTable(vhShaderTable _table)
        : table(_table) {}
};

struct VIDL_vhShaderTableSetRayGen
{
    static constexpr uint64_t kMagic = 0x2DC79CB2;
    uint64_t MAGIC = kMagic;
    vhShaderTable table;
    const char* exportName;
    nvrhi::BindingSetHandle bindingSet = nullptr;

    VIDL_vhShaderTableSetRayGen() = default;

    VIDL_vhShaderTableSetRayGen(vhShaderTable _table, const char* _exportName, nvrhi::BindingSetHandle _bindingSet)
        : table(_table), exportName(_exportName), bindingSet(_bindingSet) {}
};

struct VIDL_vhShaderTableAddMiss
{
    static constexpr uint64_t kMagic = 0xECE6D8B1;
    uint64_t MAGIC = kMagic;
    vhShaderTable table;
    const char* exportName;
    nvrhi::BindingSetHandle bindingSet = nullptr;

    VIDL_vhShaderTableAddMiss() = default;

    VIDL_vhShaderTableAddMiss(vhShaderTable _table, const char* _exportName, nvrhi::BindingSetHandle _bindingSet)
        : table(_table), exportName(_exportName), bindingSet(_bindingSet) {}
};

struct VIDL_vhShaderTableAddHitGroup
{
    static constexpr uint64_t kMagic = 0xBBF55BF8;
    uint64_t MAGIC = kMagic;
    vhShaderTable table;
    const char* exportName;
    nvrhi::BindingSetHandle bindingSet = nullptr;

    VIDL_vhShaderTableAddHitGroup() = default;

    VIDL_vhShaderTableAddHitGroup(vhShaderTable _table, const char* _exportName, nvrhi::BindingSetHandle _bindingSet)
        : table(_table), exportName(_exportName), bindingSet(_bindingSet) {}
};

struct VIDL_vhDispatchRays
{
    static constexpr uint64_t kMagic = 0x2AF23D52;
    uint64_t MAGIC = kMagic;
    vhStateId stateID;
    vhShaderTable table;
    const nvrhi::rt::DispatchRaysArguments args;

    VIDL_vhDispatchRays() = default;

    VIDL_vhDispatchRays(vhStateId _stateID, vhShaderTable _table, const nvrhi::rt::DispatchRaysArguments& _args)
        : stateID(_stateID), table(_table), args(_args) {}
};

struct VIDL_vhCreateShader
{
    static constexpr uint64_t kMagic = 0x21DB7127;
    uint64_t MAGIC = kMagic;
    vhShader shader;
    const char* name;
    uint64_t flags;
    const std::vector< uint32_t > spirv;
    const char* entry = "main";

    VIDL_vhCreateShader() = default;

    VIDL_vhCreateShader(vhShader _shader, const char* _name, uint64_t _flags, const std::vector< uint32_t >& _spirv, const char* _entry)
        : shader(_shader), name(_name), flags(_flags), spirv(_spirv), entry(_entry) {}
};

struct VIDL_vhDestroyShader
{
    static constexpr uint64_t kMagic = 0x3328C9A7;
    uint64_t MAGIC = kMagic;
    vhShader shader;

    VIDL_vhDestroyShader() = default;

    VIDL_vhDestroyShader(vhShader _shader)
        : shader(_shader) {}
};

struct VIDL_vhDispatch
{
    static constexpr uint64_t kMagic = 0x8A8ABD80;
    uint64_t MAGIC = kMagic;
    vhStateId stateID;
    glm::uvec3 workGroupCount;

    VIDL_vhDispatch() = default;

    VIDL_vhDispatch(vhStateId _stateID, glm::uvec3 _workGroupCount)
        : stateID(_stateID), workGroupCount(_workGroupCount) {}
};

struct VIDL_vhDispatchIndirect
{
    static constexpr uint64_t kMagic = 0x76CD9435;
    uint64_t MAGIC = kMagic;
    vhStateId stateID;
    vhBuffer indirectBuffer;
    uint64_t byteOffset = 0;

    VIDL_vhDispatchIndirect() = default;

    VIDL_vhDispatchIndirect(vhStateId _stateID, vhBuffer _indirectBuffer, uint64_t _byteOffset)
        : stateID(_stateID), indirectBuffer(_indirectBuffer), byteOffset(_byteOffset) {}
};

struct VIDL_vhClear
{
    static constexpr uint64_t kMagic = 0xD14CA051;
    uint64_t MAGIC = kMagic;
    vhStateId state;
    uint16_t clearFlags = VRHI_CLEAR_COLOR;

    VIDL_vhClear() = default;

    VIDL_vhClear(vhStateId _state, uint16_t _clearFlags)
        : state(_state), clearFlags(_clearFlags) {}
};

struct VIDL_vhFlushInternal
{
    static constexpr uint64_t kMagic = 0x83140D26;
    uint64_t MAGIC = kMagic;
    std::atomic<bool>* fence;
    bool waitForGPU = false;

    VIDL_vhFlushInternal() = default;

    VIDL_vhFlushInternal(std::atomic<bool>* _fence, bool _waitForGPU)
        : fence(_fence), waitForGPU(_waitForGPU) {}
};

struct VIDL_vhCmdSetStateViewRect
{
    static constexpr uint64_t kMagic = 0x25DC7E64;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    glm::vec4 rect;

    VIDL_vhCmdSetStateViewRect() = default;

    VIDL_vhCmdSetStateViewRect(vhStateId _id, glm::vec4 _rect)
        : id(_id), rect(_rect) {}
};

struct VIDL_vhCmdSetStateViewScissor
{
    static constexpr uint64_t kMagic = 0xD89EF1E1;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    glm::vec4 scissor;

    VIDL_vhCmdSetStateViewScissor() = default;

    VIDL_vhCmdSetStateViewScissor(vhStateId _id, glm::vec4 _scissor)
        : id(_id), scissor(_scissor) {}
};

struct VIDL_vhCmdSetStateViewClear
{
    static constexpr uint64_t kMagic = 0xAB6B3FB4;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    uint16_t flags;
    glm::vec4 color;
    glm::u8vec4 colorUInt;
    float depth;
    uint8_t stencil;

    VIDL_vhCmdSetStateViewClear() = default;

    VIDL_vhCmdSetStateViewClear(vhStateId _id, uint16_t _flags, glm::vec4 _color, glm::u8vec4 _colorUInt, float _depth, uint8_t _stencil)
        : id(_id), flags(_flags), color(_color), colorUInt(_colorUInt), depth(_depth), stencil(_stencil) {}
};

struct VIDL_vhCmdSetStateProgram
{
    static constexpr uint64_t kMagic = 0x106BC354;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    vhProgram program;

    VIDL_vhCmdSetStateProgram() = default;

    VIDL_vhCmdSetStateProgram(vhStateId _id, vhProgram _program)
        : id(_id), program(_program) {}
};

struct VIDL_vhCmdSetStateViewTransform
{
    static constexpr uint64_t kMagic = 0x95EE7C8C;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    glm::mat4 view;
    glm::mat4 proj;

    VIDL_vhCmdSetStateViewTransform() = default;

    VIDL_vhCmdSetStateViewTransform(vhStateId _id, glm::mat4 _view, glm::mat4 _proj)
        : id(_id), view(_view), proj(_proj) {}
};

struct VIDL_vhCmdSetStateWorldTransform
{
    static constexpr uint64_t kMagic = 0x8FB805B7;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    std::vector< glm::mat4 > matrices;

    VIDL_vhCmdSetStateWorldTransform() = default;

    VIDL_vhCmdSetStateWorldTransform(vhStateId _id, std::vector< glm::mat4 > _matrices)
        : id(_id), matrices(_matrices) {}
};

struct VIDL_vhCmdSetStateFlags
{
    static constexpr uint64_t kMagic = 0xC3CE00B4;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    uint64_t flags;

    VIDL_vhCmdSetStateFlags() = default;

    VIDL_vhCmdSetStateFlags(vhStateId _id, uint64_t _flags)
        : id(_id), flags(_flags) {}
};

struct VIDL_vhCmdSetStateDebugFlags
{
    static constexpr uint64_t kMagic = 0x9CFC0ABD;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    uint64_t flags;

    VIDL_vhCmdSetStateDebugFlags() = default;

    VIDL_vhCmdSetStateDebugFlags(vhStateId _id, uint64_t _flags)
        : id(_id), flags(_flags) {}
};

struct VIDL_vhCmdSetStateStencil
{
    static constexpr uint64_t kMagic = 0x007FD9BA;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    uint64_t stencilState;

    VIDL_vhCmdSetStateStencil() = default;

    VIDL_vhCmdSetStateStencil(vhStateId _id, uint64_t _stencilState)
        : id(_id), stencilState(_stencilState) {}
};

struct VIDL_vhCmdSetStateDepthBias
{
    static constexpr uint64_t kMagic = 0x3290E5BB;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    int bias;
    float clamp;
    float slopeScaled;

    VIDL_vhCmdSetStateDepthBias() = default;

    VIDL_vhCmdSetStateDepthBias(vhStateId _id, int _bias, float _clamp, float _slopeScaled)
        : id(_id), bias(_bias), clamp(_clamp), slopeScaled(_slopeScaled) {}
};

struct VIDL_vhCmdSetStateVertexBuffer
{
    static constexpr uint64_t kMagic = 0xF0E68F37;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    uint8_t stream;
    vhBuffer buffer;
    uint64_t offset;
    uint32_t start;
    uint32_t num;

    VIDL_vhCmdSetStateVertexBuffer() = default;

    VIDL_vhCmdSetStateVertexBuffer(vhStateId _id, uint8_t _stream, vhBuffer _buffer, uint64_t _offset, uint32_t _start, uint32_t _num)
        : id(_id), stream(_stream), buffer(_buffer), offset(_offset), start(_start), num(_num) {}
};

struct VIDL_vhCmdSetStateIndexBuffer
{
    static constexpr uint64_t kMagic = 0xE36C062A;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    vhBuffer buffer;
    uint64_t offset;
    uint32_t first;
    uint32_t num;

    VIDL_vhCmdSetStateIndexBuffer() = default;

    VIDL_vhCmdSetStateIndexBuffer(vhStateId _id, vhBuffer _buffer, uint64_t _offset, uint32_t _first, uint32_t _num)
        : id(_id), buffer(_buffer), offset(_offset), first(_first), num(_num) {}
};

struct VIDL_vhCmdSetStateTextures
{
    static constexpr uint64_t kMagic = 0x3A615501;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    const std::vector< vhState::TextureBinding > textures;

    VIDL_vhCmdSetStateTextures() = default;

    VIDL_vhCmdSetStateTextures(vhStateId _id, const std::vector< vhState::TextureBinding >& _textures)
        : id(_id), textures(_textures) {}
};

struct VIDL_vhCmdSetStateSamplers
{
    static constexpr uint64_t kMagic = 0xFCB052A2;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    const std::vector< vhState::SamplerDefinition > samplers;

    VIDL_vhCmdSetStateSamplers() = default;

    VIDL_vhCmdSetStateSamplers(vhStateId _id, const std::vector< vhState::SamplerDefinition >& _samplers)
        : id(_id), samplers(_samplers) {}
};

struct VIDL_vhCmdSetStateBuffers
{
    static constexpr uint64_t kMagic = 0x953A85B6;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    const std::vector< vhState::BufferBinding > buffers;

    VIDL_vhCmdSetStateBuffers() = default;

    VIDL_vhCmdSetStateBuffers(vhStateId _id, const std::vector< vhState::BufferBinding >& _buffers)
        : id(_id), buffers(_buffers) {}
};

struct VIDL_vhCmdSetStateConstants
{
    static constexpr uint64_t kMagic = 0x23287787;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    const std::vector< vhState::ConstantBufferValue > constants;

    VIDL_vhCmdSetStateConstants() = default;

    VIDL_vhCmdSetStateConstants(vhStateId _id, const std::vector< vhState::ConstantBufferValue >& _constants)
        : id(_id), constants(_constants) {}
};

struct VIDL_vhCmdSetStatePushConstants
{
    static constexpr uint64_t kMagic = 0x0A9462A0;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    glm::vec4 data;

    VIDL_vhCmdSetStatePushConstants() = default;

    VIDL_vhCmdSetStatePushConstants(vhStateId _id, glm::vec4 _data)
        : id(_id), data(_data) {}
};

struct VIDL_vhCmdSetStateUniforms
{
    static constexpr uint64_t kMagic = 0xAB3B2AB3;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    const std::vector< vhState::UniformBufferValue > uniforms;

    VIDL_vhCmdSetStateUniforms() = default;

    VIDL_vhCmdSetStateUniforms(vhStateId _id, const std::vector< vhState::UniformBufferValue >& _uniforms)
        : id(_id), uniforms(_uniforms) {}
};

struct VIDL_vhCmdSetStateAttachments
{
    static constexpr uint64_t kMagic = 0xD3B53061;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    const std::vector< vhState::RenderTarget > colours;
    vhState::RenderTarget depth;

    VIDL_vhCmdSetStateAttachments() = default;

    VIDL_vhCmdSetStateAttachments(vhStateId _id, const std::vector< vhState::RenderTarget >& _colours, vhState::RenderTarget _depth)
        : id(_id), colours(_colours), depth(_depth) {}
};

struct VIDL_vhCmdSetStateBlendConstants
{
    static constexpr uint64_t kMagic = 0xFEEBA1AD;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    glm::vec4 blendConst;

    VIDL_vhCmdSetStateBlendConstants() = default;

    VIDL_vhCmdSetStateBlendConstants(vhStateId _id, glm::vec4 _blendConst)
        : id(_id), blendConst(_blendConst) {}
};

struct VIDL_vhCmdSetStateViewDepthRange
{
    static constexpr uint64_t kMagic = 0x251DEFAB;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    float minZ;
    float maxZ;

    VIDL_vhCmdSetStateViewDepthRange() = default;

    VIDL_vhCmdSetStateViewDepthRange(vhStateId _id, float _minZ, float _maxZ)
        : id(_id), minZ(_minZ), maxZ(_maxZ) {}
};

struct VIDL_vhCmdSetStateShadingRate
{
    static constexpr uint64_t kMagic = 0xD7406BFA;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    uint32_t flags;
    vhTexture image;

    VIDL_vhCmdSetStateShadingRate() = default;

    VIDL_vhCmdSetStateShadingRate(vhStateId _id, uint32_t _flags, vhTexture _image)
        : id(_id), flags(_flags), image(_image) {}
};

struct VIDL_vhCmdSetStateIndirectParams
{
    static constexpr uint64_t kMagic = 0xE435C0DD;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    vhBuffer buffer;
    uint64_t offset;

    VIDL_vhCmdSetStateIndirectParams() = default;

    VIDL_vhCmdSetStateIndirectParams(vhStateId _id, vhBuffer _buffer, uint64_t _offset)
        : id(_id), buffer(_buffer), offset(_offset) {}
};

struct VIDL_vhCmdSetStateAccelStructs
{
    static constexpr uint64_t kMagic = 0x16DF2363;
    uint64_t MAGIC = kMagic;
    vhStateId id;
    const std::vector< vhState::AccelStructBinding > accelStructs;

    VIDL_vhCmdSetStateAccelStructs() = default;

    VIDL_vhCmdSetStateAccelStructs(vhStateId _id, const std::vector< vhState::AccelStructBinding >& _accelStructs)
        : id(_id), accelStructs(_accelStructs) {}
};

struct VIDL_vhDrawCommonInternal
{
    static constexpr uint64_t kMagic = 0x8827DC81;
    uint64_t MAGIC = kMagic;
    vhStateId state;
    uint32_t flags;
    uint32_t vertexCount;
    uint32_t instanceCount;
    uint32_t startVertexLocation;
    uint32_t startIndexLocation;
    uint32_t startInstanceLocation;
    uint32_t drawCount;

    VIDL_vhDrawCommonInternal() = default;

    VIDL_vhDrawCommonInternal(vhStateId _state, uint32_t _flags, uint32_t _vertexCount, uint32_t _instanceCount, uint32_t _startVertexLocation, uint32_t _startIndexLocation, uint32_t _startInstanceLocation, uint32_t _drawCount)
        : state(_state), flags(_flags), vertexCount(_vertexCount), instanceCount(_instanceCount), startVertexLocation(_startVertexLocation), startIndexLocation(_startIndexLocation), startInstanceLocation(_startInstanceLocation), drawCount(_drawCount) {}
};

struct VIDLHandler
{
    virtual void Handle_vhResizeCleanup( VIDL_vhResizeCleanup* cmd ) { (void) cmd; };
    virtual void Handle_vhBeginTimerQuery( VIDL_vhBeginTimerQuery* cmd ) { (void) cmd; };
    virtual void Handle_vhEndTimerQuery( VIDL_vhEndTimerQuery* cmd ) { (void) cmd; };
    virtual void Handle_vhBeginMarker( VIDL_vhBeginMarker* cmd ) { (void) cmd; };
    virtual void Handle_vhEndMarker( VIDL_vhEndMarker* cmd ) { (void) cmd; };
    virtual void Handle_vhCaptureStart( VIDL_vhCaptureStart* cmd ) { (void) cmd; };
    virtual void Handle_vhCaptureEnd( VIDL_vhCaptureEnd* cmd ) { (void) cmd; };
    virtual void Handle_vhResetTexture( VIDL_vhResetTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhResetBuffer( VIDL_vhResetBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhDestroyTexture( VIDL_vhDestroyTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateTexture( VIDL_vhCreateTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhUpdateTexture( VIDL_vhUpdateTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhReadTextureSlow( VIDL_vhReadTextureSlow* cmd ) { (void) cmd; };
    virtual void Handle_vhBlitTexture( VIDL_vhBlitTexture* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateVertexBuffer( VIDL_vhCreateVertexBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhUpdateVertexBuffer( VIDL_vhUpdateVertexBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateIndexBuffer( VIDL_vhCreateIndexBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhUpdateIndexBuffer( VIDL_vhUpdateIndexBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateUniformBuffer( VIDL_vhCreateUniformBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhUpdateUniformBuffer( VIDL_vhUpdateUniformBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateStorageBuffer( VIDL_vhCreateStorageBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhUpdateStorageBuffer( VIDL_vhUpdateStorageBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhBlitBuffer( VIDL_vhBlitBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhDestroyBuffer( VIDL_vhDestroyBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateAS( VIDL_vhCreateAS* cmd ) { (void) cmd; };
    virtual void Handle_vhDestroyAS( VIDL_vhDestroyAS* cmd ) { (void) cmd; };
    virtual void Handle_vhBuildBLAS( VIDL_vhBuildBLAS* cmd ) { (void) cmd; };
    virtual void Handle_vhBuildTLAS( VIDL_vhBuildTLAS* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateRTPipeline( VIDL_vhCreateRTPipeline* cmd ) { (void) cmd; };
    virtual void Handle_vhDestroyRTPipeline( VIDL_vhDestroyRTPipeline* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateShaderTable( VIDL_vhCreateShaderTable* cmd ) { (void) cmd; };
    virtual void Handle_vhDestroyShaderTable( VIDL_vhDestroyShaderTable* cmd ) { (void) cmd; };
    virtual void Handle_vhShaderTableSetRayGen( VIDL_vhShaderTableSetRayGen* cmd ) { (void) cmd; };
    virtual void Handle_vhShaderTableAddMiss( VIDL_vhShaderTableAddMiss* cmd ) { (void) cmd; };
    virtual void Handle_vhShaderTableAddHitGroup( VIDL_vhShaderTableAddHitGroup* cmd ) { (void) cmd; };
    virtual void Handle_vhDispatchRays( VIDL_vhDispatchRays* cmd ) { (void) cmd; };
    virtual void Handle_vhCreateShader( VIDL_vhCreateShader* cmd ) { (void) cmd; };
    virtual void Handle_vhDestroyShader( VIDL_vhDestroyShader* cmd ) { (void) cmd; };
    virtual void Handle_vhDispatch( VIDL_vhDispatch* cmd ) { (void) cmd; };
    virtual void Handle_vhDispatchIndirect( VIDL_vhDispatchIndirect* cmd ) { (void) cmd; };
    virtual void Handle_vhClear( VIDL_vhClear* cmd ) { (void) cmd; };
    virtual void Handle_vhFlushInternal( VIDL_vhFlushInternal* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateViewRect( VIDL_vhCmdSetStateViewRect* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateViewScissor( VIDL_vhCmdSetStateViewScissor* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateViewClear( VIDL_vhCmdSetStateViewClear* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateProgram( VIDL_vhCmdSetStateProgram* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateViewTransform( VIDL_vhCmdSetStateViewTransform* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateWorldTransform( VIDL_vhCmdSetStateWorldTransform* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateFlags( VIDL_vhCmdSetStateFlags* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateDebugFlags( VIDL_vhCmdSetStateDebugFlags* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateStencil( VIDL_vhCmdSetStateStencil* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateDepthBias( VIDL_vhCmdSetStateDepthBias* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateVertexBuffer( VIDL_vhCmdSetStateVertexBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateIndexBuffer( VIDL_vhCmdSetStateIndexBuffer* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateTextures( VIDL_vhCmdSetStateTextures* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateSamplers( VIDL_vhCmdSetStateSamplers* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateBuffers( VIDL_vhCmdSetStateBuffers* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateConstants( VIDL_vhCmdSetStateConstants* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStatePushConstants( VIDL_vhCmdSetStatePushConstants* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateUniforms( VIDL_vhCmdSetStateUniforms* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateAttachments( VIDL_vhCmdSetStateAttachments* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateBlendConstants( VIDL_vhCmdSetStateBlendConstants* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateViewDepthRange( VIDL_vhCmdSetStateViewDepthRange* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateShadingRate( VIDL_vhCmdSetStateShadingRate* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateIndirectParams( VIDL_vhCmdSetStateIndirectParams* cmd ) { (void) cmd; };
    virtual void Handle_vhCmdSetStateAccelStructs( VIDL_vhCmdSetStateAccelStructs* cmd ) { (void) cmd; };
    virtual void Handle_vhDrawCommonInternal( VIDL_vhDrawCommonInternal* cmd ) { (void) cmd; };

    virtual void HandleLogFunction( const char* str ) {};

    virtual void HandleCmd( void* cmd )
    {
        uint64_t magic = *(uint64_t*)cmd;
        switch ( magic )
        {
        case 0xF3F4A7CF:
            HandleLogFunction("Handle_vhResizeCleanup");
            Handle_vhResizeCleanup( (VIDL_vhResizeCleanup*) cmd );
            break;
        case 0x178A2421:
            HandleLogFunction("Handle_vhBeginTimerQuery");
            Handle_vhBeginTimerQuery( (VIDL_vhBeginTimerQuery*) cmd );
            break;
        case 0x130A84AE:
            HandleLogFunction("Handle_vhEndTimerQuery");
            Handle_vhEndTimerQuery( (VIDL_vhEndTimerQuery*) cmd );
            break;
        case 0x2631B4CA:
            HandleLogFunction("Handle_vhBeginMarker");
            Handle_vhBeginMarker( (VIDL_vhBeginMarker*) cmd );
            break;
        case 0xFA453E7B:
            HandleLogFunction("Handle_vhEndMarker");
            Handle_vhEndMarker( (VIDL_vhEndMarker*) cmd );
            break;
        case 0x45A5468F:
            HandleLogFunction("Handle_vhCaptureStart");
            Handle_vhCaptureStart( (VIDL_vhCaptureStart*) cmd );
            break;
        case 0x165DAA75:
            HandleLogFunction("Handle_vhCaptureEnd");
            Handle_vhCaptureEnd( (VIDL_vhCaptureEnd*) cmd );
            break;
        case 0xE74D1798:
            HandleLogFunction("Handle_vhResetTexture");
            Handle_vhResetTexture( (VIDL_vhResetTexture*) cmd );
            break;
        case 0x19331E16:
            HandleLogFunction("Handle_vhResetBuffer");
            Handle_vhResetBuffer( (VIDL_vhResetBuffer*) cmd );
            break;
        case 0xC090699A:
            HandleLogFunction("Handle_vhDestroyTexture");
            Handle_vhDestroyTexture( (VIDL_vhDestroyTexture*) cmd );
            break;
        case 0xB40533D3:
            HandleLogFunction("Handle_vhCreateTexture");
            Handle_vhCreateTexture( (VIDL_vhCreateTexture*) cmd );
            break;
        case 0x79B006BB:
            HandleLogFunction("Handle_vhUpdateTexture");
            Handle_vhUpdateTexture( (VIDL_vhUpdateTexture*) cmd );
            break;
        case 0x3BDDAB67:
            HandleLogFunction("Handle_vhReadTextureSlow");
            Handle_vhReadTextureSlow( (VIDL_vhReadTextureSlow*) cmd );
            break;
        case 0xD7782E0F:
            HandleLogFunction("Handle_vhBlitTexture");
            Handle_vhBlitTexture( (VIDL_vhBlitTexture*) cmd );
            break;
        case 0xBBF8D184:
            HandleLogFunction("Handle_vhCreateVertexBuffer");
            Handle_vhCreateVertexBuffer( (VIDL_vhCreateVertexBuffer*) cmd );
            break;
        case 0x57AF47B4:
            HandleLogFunction("Handle_vhUpdateVertexBuffer");
            Handle_vhUpdateVertexBuffer( (VIDL_vhUpdateVertexBuffer*) cmd );
            break;
        case 0x22AE59E6:
            HandleLogFunction("Handle_vhCreateIndexBuffer");
            Handle_vhCreateIndexBuffer( (VIDL_vhCreateIndexBuffer*) cmd );
            break;
        case 0x6B219F18:
            HandleLogFunction("Handle_vhUpdateIndexBuffer");
            Handle_vhUpdateIndexBuffer( (VIDL_vhUpdateIndexBuffer*) cmd );
            break;
        case 0x2EFADC4C:
            HandleLogFunction("Handle_vhCreateUniformBuffer");
            Handle_vhCreateUniformBuffer( (VIDL_vhCreateUniformBuffer*) cmd );
            break;
        case 0xD6050AA7:
            HandleLogFunction("Handle_vhUpdateUniformBuffer");
            Handle_vhUpdateUniformBuffer( (VIDL_vhUpdateUniformBuffer*) cmd );
            break;
        case 0x797A3950:
            HandleLogFunction("Handle_vhCreateStorageBuffer");
            Handle_vhCreateStorageBuffer( (VIDL_vhCreateStorageBuffer*) cmd );
            break;
        case 0x6153A4D9:
            HandleLogFunction("Handle_vhUpdateStorageBuffer");
            Handle_vhUpdateStorageBuffer( (VIDL_vhUpdateStorageBuffer*) cmd );
            break;
        case 0x15BFFC71:
            HandleLogFunction("Handle_vhBlitBuffer");
            Handle_vhBlitBuffer( (VIDL_vhBlitBuffer*) cmd );
            break;
        case 0x3A87A73E:
            HandleLogFunction("Handle_vhDestroyBuffer");
            Handle_vhDestroyBuffer( (VIDL_vhDestroyBuffer*) cmd );
            break;
        case 0xB7F81FE0:
            HandleLogFunction("Handle_vhCreateAS");
            Handle_vhCreateAS( (VIDL_vhCreateAS*) cmd );
            break;
        case 0xC034F291:
            HandleLogFunction("Handle_vhDestroyAS");
            Handle_vhDestroyAS( (VIDL_vhDestroyAS*) cmd );
            break;
        case 0xDBB4E9AB:
            HandleLogFunction("Handle_vhBuildBLAS");
            Handle_vhBuildBLAS( (VIDL_vhBuildBLAS*) cmd );
            break;
        case 0xBAF93377:
            HandleLogFunction("Handle_vhBuildTLAS");
            Handle_vhBuildTLAS( (VIDL_vhBuildTLAS*) cmd );
            break;
        case 0xF080D7EA:
            HandleLogFunction("Handle_vhCreateRTPipeline");
            Handle_vhCreateRTPipeline( (VIDL_vhCreateRTPipeline*) cmd );
            break;
        case 0x5AA337AF:
            HandleLogFunction("Handle_vhDestroyRTPipeline");
            Handle_vhDestroyRTPipeline( (VIDL_vhDestroyRTPipeline*) cmd );
            break;
        case 0x9DDDDA05:
            HandleLogFunction("Handle_vhCreateShaderTable");
            Handle_vhCreateShaderTable( (VIDL_vhCreateShaderTable*) cmd );
            break;
        case 0x6950CD93:
            HandleLogFunction("Handle_vhDestroyShaderTable");
            Handle_vhDestroyShaderTable( (VIDL_vhDestroyShaderTable*) cmd );
            break;
        case 0x2DC79CB2:
            HandleLogFunction("Handle_vhShaderTableSetRayGen");
            Handle_vhShaderTableSetRayGen( (VIDL_vhShaderTableSetRayGen*) cmd );
            break;
        case 0xECE6D8B1:
            HandleLogFunction("Handle_vhShaderTableAddMiss");
            Handle_vhShaderTableAddMiss( (VIDL_vhShaderTableAddMiss*) cmd );
            break;
        case 0xBBF55BF8:
            HandleLogFunction("Handle_vhShaderTableAddHitGroup");
            Handle_vhShaderTableAddHitGroup( (VIDL_vhShaderTableAddHitGroup*) cmd );
            break;
        case 0x2AF23D52:
            HandleLogFunction("Handle_vhDispatchRays");
            Handle_vhDispatchRays( (VIDL_vhDispatchRays*) cmd );
            break;
        case 0x21DB7127:
            HandleLogFunction("Handle_vhCreateShader");
            Handle_vhCreateShader( (VIDL_vhCreateShader*) cmd );
            break;
        case 0x3328C9A7:
            HandleLogFunction("Handle_vhDestroyShader");
            Handle_vhDestroyShader( (VIDL_vhDestroyShader*) cmd );
            break;
        case 0x8A8ABD80:
            HandleLogFunction("Handle_vhDispatch");
            Handle_vhDispatch( (VIDL_vhDispatch*) cmd );
            break;
        case 0x76CD9435:
            HandleLogFunction("Handle_vhDispatchIndirect");
            Handle_vhDispatchIndirect( (VIDL_vhDispatchIndirect*) cmd );
            break;
        case 0xD14CA051:
            HandleLogFunction("Handle_vhClear");
            Handle_vhClear( (VIDL_vhClear*) cmd );
            break;
        case 0x83140D26:
            HandleLogFunction("Handle_vhFlushInternal");
            Handle_vhFlushInternal( (VIDL_vhFlushInternal*) cmd );
            break;
        case 0x25DC7E64:
            HandleLogFunction("Handle_vhCmdSetStateViewRect");
            Handle_vhCmdSetStateViewRect( (VIDL_vhCmdSetStateViewRect*) cmd );
            break;
        case 0xD89EF1E1:
            HandleLogFunction("Handle_vhCmdSetStateViewScissor");
            Handle_vhCmdSetStateViewScissor( (VIDL_vhCmdSetStateViewScissor*) cmd );
            break;
        case 0xAB6B3FB4:
            HandleLogFunction("Handle_vhCmdSetStateViewClear");
            Handle_vhCmdSetStateViewClear( (VIDL_vhCmdSetStateViewClear*) cmd );
            break;
        case 0x106BC354:
            HandleLogFunction("Handle_vhCmdSetStateProgram");
            Handle_vhCmdSetStateProgram( (VIDL_vhCmdSetStateProgram*) cmd );
            break;
        case 0x95EE7C8C:
            HandleLogFunction("Handle_vhCmdSetStateViewTransform");
            Handle_vhCmdSetStateViewTransform( (VIDL_vhCmdSetStateViewTransform*) cmd );
            break;
        case 0x8FB805B7:
            HandleLogFunction("Handle_vhCmdSetStateWorldTransform");
            Handle_vhCmdSetStateWorldTransform( (VIDL_vhCmdSetStateWorldTransform*) cmd );
            break;
        case 0xC3CE00B4:
            HandleLogFunction("Handle_vhCmdSetStateFlags");
            Handle_vhCmdSetStateFlags( (VIDL_vhCmdSetStateFlags*) cmd );
            break;
        case 0x9CFC0ABD:
            HandleLogFunction("Handle_vhCmdSetStateDebugFlags");
            Handle_vhCmdSetStateDebugFlags( (VIDL_vhCmdSetStateDebugFlags*) cmd );
            break;
        case 0x007FD9BA:
            HandleLogFunction("Handle_vhCmdSetStateStencil");
            Handle_vhCmdSetStateStencil( (VIDL_vhCmdSetStateStencil*) cmd );
            break;
        case 0x3290E5BB:
            HandleLogFunction("Handle_vhCmdSetStateDepthBias");
            Handle_vhCmdSetStateDepthBias( (VIDL_vhCmdSetStateDepthBias*) cmd );
            break;
        case 0xF0E68F37:
            HandleLogFunction("Handle_vhCmdSetStateVertexBuffer");
            Handle_vhCmdSetStateVertexBuffer( (VIDL_vhCmdSetStateVertexBuffer*) cmd );
            break;
        case 0xE36C062A:
            HandleLogFunction("Handle_vhCmdSetStateIndexBuffer");
            Handle_vhCmdSetStateIndexBuffer( (VIDL_vhCmdSetStateIndexBuffer*) cmd );
            break;
        case 0x3A615501:
            HandleLogFunction("Handle_vhCmdSetStateTextures");
            Handle_vhCmdSetStateTextures( (VIDL_vhCmdSetStateTextures*) cmd );
            break;
        case 0xFCB052A2:
            HandleLogFunction("Handle_vhCmdSetStateSamplers");
            Handle_vhCmdSetStateSamplers( (VIDL_vhCmdSetStateSamplers*) cmd );
            break;
        case 0x953A85B6:
            HandleLogFunction("Handle_vhCmdSetStateBuffers");
            Handle_vhCmdSetStateBuffers( (VIDL_vhCmdSetStateBuffers*) cmd );
            break;
        case 0x23287787:
            HandleLogFunction("Handle_vhCmdSetStateConstants");
            Handle_vhCmdSetStateConstants( (VIDL_vhCmdSetStateConstants*) cmd );
            break;
        case 0x0A9462A0:
            HandleLogFunction("Handle_vhCmdSetStatePushConstants");
            Handle_vhCmdSetStatePushConstants( (VIDL_vhCmdSetStatePushConstants*) cmd );
            break;
        case 0xAB3B2AB3:
            HandleLogFunction("Handle_vhCmdSetStateUniforms");
            Handle_vhCmdSetStateUniforms( (VIDL_vhCmdSetStateUniforms*) cmd );
            break;
        case 0xD3B53061:
            HandleLogFunction("Handle_vhCmdSetStateAttachments");
            Handle_vhCmdSetStateAttachments( (VIDL_vhCmdSetStateAttachments*) cmd );
            break;
        case 0xFEEBA1AD:
            HandleLogFunction("Handle_vhCmdSetStateBlendConstants");
            Handle_vhCmdSetStateBlendConstants( (VIDL_vhCmdSetStateBlendConstants*) cmd );
            break;
        case 0x251DEFAB:
            HandleLogFunction("Handle_vhCmdSetStateViewDepthRange");
            Handle_vhCmdSetStateViewDepthRange( (VIDL_vhCmdSetStateViewDepthRange*) cmd );
            break;
        case 0xD7406BFA:
            HandleLogFunction("Handle_vhCmdSetStateShadingRate");
            Handle_vhCmdSetStateShadingRate( (VIDL_vhCmdSetStateShadingRate*) cmd );
            break;
        case 0xE435C0DD:
            HandleLogFunction("Handle_vhCmdSetStateIndirectParams");
            Handle_vhCmdSetStateIndirectParams( (VIDL_vhCmdSetStateIndirectParams*) cmd );
            break;
        case 0x16DF2363:
            HandleLogFunction("Handle_vhCmdSetStateAccelStructs");
            Handle_vhCmdSetStateAccelStructs( (VIDL_vhCmdSetStateAccelStructs*) cmd );
            break;
        case 0x8827DC81:
            HandleLogFunction("Handle_vhDrawCommonInternal");
            Handle_vhDrawCommonInternal( (VIDL_vhDrawCommonInternal*) cmd );
            break;
        }
    }
};